// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.9999783627140504
//mw 0.9995185942767729
//sw 0.9833264407199804
//dbl 0.9998650425894595


// Generated: 2019/5/27   14:52:7


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Olympus_PEN_E_PL5_Olympus_60mm_f2_8_VK6R_to_Triggerfish_5mGreenWater implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] vR;
float[] vG;
float[] vB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];
float[] dbl = new float[dimension];

vR = (float[]) stack.getPixels(1);
vG = (float[]) stack.getPixels(2);
vB = (float[]) stack.getPixels(3);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (-1.1549353074595204E-4 +(vR[i]*-9.546549902483936E-4)+(vG[i]*0.010035530458974918)+(vB[i]*9.026787658501157E-4)+(vR[i]*vG[i]*-5.579454765122957E-7)+(vR[i]*vB[i]*9.247570745022455E-7)+(vG[i]*vB[i]*-8.051816774728085E-8));
mw[i] = (float) (-0.0022838788794359993 +(vR[i]*-9.52518875867176E-4)+(vG[i]*0.002995520855116672)+(vB[i]*0.008016597372161809)+(vR[i]*vG[i]*-3.084842476675229E-6)+(vR[i]*vB[i]*5.890712124895531E-6)+(vG[i]*vB[i]*-2.698852532057108E-6));
sw[i] = (float) (0.017833271930975544 +(vR[i]*0.0017769741360994541)+(vG[i]*-0.007442303917254324)+(vB[i]*0.013723381955416057)+(vR[i]*vG[i]*8.630649400298398E-6)+(vR[i]*vB[i]*4.289930964105652E-7)+(vG[i]*vB[i]*4.95702440782627E-6));
dbl[i] = (float) (-0.0010041248518352596 +(vR[i]*-9.537978705108598E-4)+(vG[i]*0.007149781030407808)+(vB[i]*0.0038187373339997606)+(vR[i]*vG[i]*-1.5933844396524469E-6)+(vR[i]*vB[i]*2.9595678077137106E-6)+(vG[i]*vB[i]*-1.1533670355685717E-6));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
outStack.addSlice("dbl", dbl);
new ImagePlus("Output", outStack).show();

}
}
