// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.99982387535606
//mw 0.9983138774323107
//sw 0.9894929236057007
//dbl 0.9993845805262271


// Generated: 2019/5/17   11:21:55


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Olympus_PEN_E_PL5_Olympus_60mm_f2_8_PV62white_VK6R_Combined_to_Triggerfish_5m_green_water implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] vR;
float[] vG;
float[] vB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];
float[] dbl = new float[dimension];

vR = (float[]) stack.getPixels(1);
vG = (float[]) stack.getPixels(2);
vB = (float[]) stack.getPixels(3);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (-0.001315977638569774 +(vR[i]*-0.0010203971489906797)+(vG[i]*0.009854575540051336)+(vB[i]*0.0012191295648442907)+(vR[i]*vG[i]*-1.169825943286344E-6)+(vR[i]*vB[i]*1.6765760966978968E-6)+(vG[i]*vB[i]*-5.330831585761155E-7));
mw[i] = (float) (-0.004537113185422996 +(vR[i]*-0.001281582060397099)+(vG[i]*0.0036698065387742247)+(vB[i]*0.007828308403119029)+(vR[i]*vG[i]*-3.2063109804664883E-6)+(vR[i]*vB[i]*4.8391365916425535E-6)+(vG[i]*vB[i]*-2.2797069889858035E-6));
sw[i] = (float) (0.013777983472102885 +(vR[i]*0.0015494265478719815)+(vG[i]*-0.006161616649638136)+(vB[i]*0.012991847859930702)+(vR[i]*vG[i]*2.288036532395136E-6)+(vR[i]*vB[i]*6.467208642101469E-6)+(vG[i]*vB[i]*3.4419298399725102E-6));
dbl[i] = (float) (-0.002636147126451364 +(vR[i]*-0.0011274791145414866)+(vG[i]*0.007319398497556757)+(vB[i]*0.0039282910236800635)+(vR[i]*vG[i]*-2.0042879064393937E-6)+(vR[i]*vB[i]*2.9722282248824732E-6)+(vG[i]*vB[i]*-1.248637383971243E-6));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
outStack.addSlice("dbl", dbl);
new ImagePlus("Output", outStack).show();

}
}
