// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.998832290862767
//mw 0.9997261218770082
//sw 0.9992510738243842
//uv 0.9989205201453796
//dbl 0.9998077484027971


// Generated: 2019/5/3   19:28:15


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Nikon_D7000_Novoflex_35mm_D65_to_Bluetit_D65 implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] vR;
float[] vG;
float[] vB;
float[] uB;
float[] uR;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];
float[] uv = new float[dimension];
float[] dbl = new float[dimension];

vR = (float[]) stack.getPixels(1);
vG = (float[]) stack.getPixels(2);
vB = (float[]) stack.getPixels(3);
uB = (float[]) stack.getPixels(4);
uR = (float[]) stack.getPixels(5);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (-0.004359186803880861 +(vR[i]*0.009214202410366194)+(vG[i]*0.003750941446824748)+(vB[i]*-0.003467156471160739)+(uB[i]*0.0017382048536973534)+(uR[i]*-0.0015158525968921542)+(vR[i]*vG[i]*-1.721292064270903E-5)+(vR[i]*vB[i]*1.0493413372455563E-5)+(vR[i]*uB[i]*-1.0906814344809348E-4)+(vR[i]*uR[i]*1.2471533926938216E-4)+(vG[i]*vB[i]*2.107419424238719E-5)+(vG[i]*uB[i]*1.7907459587256417E-4)+(vG[i]*uR[i]*-2.4545169146657583E-4)+(vB[i]*uB[i]*-1.0910514573699115E-4)+(vB[i]*uR[i]*1.5845630190319173E-4)+(uB[i]*uR[i]*-3.7380501954549707E-6)+(vR[i]*vG[i]*vB[i]*-9.033573814942216E-8)+(vR[i]*vG[i]*uB[i]*-6.724848654037217E-7)+(vR[i]*vG[i]*uR[i]*1.2165164476767683E-6)+(vR[i]*vB[i]*uB[i]*5.188272190122281E-6)+(vR[i]*vB[i]*uR[i]*-5.99572737250658E-6)+(vR[i]*uB[i]*uR[i]*-4.055428131356443E-8)+(vG[i]*vB[i]*uB[i]*-4.354265382770794E-6)+(vG[i]*vB[i]*uR[i]*4.527869044416561E-6)+(vG[i]*uB[i]*uR[i]*5.759591483656987E-7)+(vB[i]*uB[i]*uR[i]*-4.1596853423798054E-7));
mw[i] = (float) (0.0015283603384587572 +(vR[i]*-0.0017325307992344242)+(vG[i]*0.016123630790097605)+(vB[i]*-0.004165130047668422)+(uB[i]*-2.3310970427473397E-4)+(uR[i]*7.60024788108941E-5)+(vR[i]*vG[i]*-9.237558281012855E-7)+(vR[i]*vB[i]*2.090484303878733E-6)+(vR[i]*uB[i]*9.55409067887834E-6)+(vR[i]*uR[i]*-1.014994509467249E-6)+(vG[i]*vB[i]*-1.4814432437111494E-5)+(vG[i]*uB[i]*-7.000510964960327E-5)+(vG[i]*uR[i]*4.556735457366218E-5)+(vB[i]*uB[i]*7.347251683727077E-5)+(vB[i]*uR[i]*-4.8771741107155934E-5)+(uB[i]*uR[i]*1.3799531399233405E-6)+(vR[i]*vG[i]*vB[i]*1.062845815881063E-7)+(vR[i]*vG[i]*uB[i]*3.430116570652555E-7)+(vR[i]*vG[i]*uR[i]*-2.923551026777119E-7)+(vR[i]*vB[i]*uB[i]*-4.4057115953952674E-7)+(vR[i]*vB[i]*uR[i]*-5.474782169934933E-8)+(vR[i]*uB[i]*uR[i]*1.0581581306621915E-7)+(vG[i]*vB[i]*uB[i]*1.387723228820835E-7)+(vG[i]*vB[i]*uR[i]*2.1929471087279213E-7)+(vG[i]*uB[i]*uR[i]*1.5313846087354752E-7)+(vB[i]*uB[i]*uR[i]*-2.494726622046495E-7));
sw[i] = (float) (-5.1318595465120204E-5 +(vR[i]*1.6953859171556348E-4)+(vG[i]*-0.0018972127057253851)+(vB[i]*0.011432410461495518)+(uB[i]*0.0011038409867333164)+(uR[i]*-7.146130394907558E-4)+(vR[i]*vG[i]*-1.8388225588620506E-6)+(vR[i]*vB[i]*-8.23780655933166E-6)+(vR[i]*uB[i]*-1.963620025948026E-5)+(vR[i]*uR[i]*3.566059523879833E-5)+(vG[i]*vB[i]*-7.259877064223096E-6)+(vG[i]*uB[i]*-3.739136664383761E-5)+(vG[i]*uR[i]*2.5810262616494953E-6)+(vB[i]*uB[i]*7.041964054346234E-5)+(vB[i]*uR[i]*-2.491080117911223E-5)+(uB[i]*uR[i]*-1.297853856929696E-5)+(vR[i]*vG[i]*vB[i]*1.5277907269715218E-7)+(vR[i]*vG[i]*uB[i]*3.6610250474729525E-7)+(vR[i]*vG[i]*uR[i]*-3.365138275073521E-7)+(vR[i]*vB[i]*uB[i]*8.404673355841984E-7)+(vR[i]*vB[i]*uR[i]*-1.2025700110062902E-6)+(vR[i]*uB[i]*uR[i]*-6.535916633923917E-8)+(vG[i]*vB[i]*uB[i]*-1.1498515187894822E-6)+(vG[i]*vB[i]*uR[i]*1.1090334355036159E-6)+(vG[i]*uB[i]*uR[i]*7.352268583955545E-7)+(vB[i]*uB[i]*uR[i]*-4.194713137789564E-7));
uv[i] = (float) (-2.5505656353991973E-4 +(vR[i]*1.4776773679712584E-4)+(vG[i]*-4.21215697429292E-4)+(vB[i]*0.0010922964747164805)+(uB[i]*0.0038383298328402973)+(uR[i]*0.005343717236593313)+(vR[i]*vG[i]*-5.919913952990445E-7)+(vR[i]*vB[i]*-8.816687761162493E-6)+(vR[i]*uB[i]*7.909741926249146E-6)+(vR[i]*uR[i]*8.434961561515217E-6)+(vG[i]*vB[i]*-6.789189442964176E-6)+(vG[i]*uB[i]*-3.390148875925468E-5)+(vG[i]*uR[i]*7.263305588854027E-6)+(vB[i]*uB[i]*7.278410585738706E-5)+(vB[i]*uR[i]*7.14459596002347E-8)+(uB[i]*uR[i]*-4.809604607992458E-5)+(vR[i]*vG[i]*vB[i]*1.617785238152056E-7)+(vR[i]*vG[i]*uB[i]*3.4385202944223934E-7)+(vR[i]*vG[i]*uR[i]*-3.546638159422596E-7)+(vR[i]*vB[i]*uB[i]*3.440832585710413E-7)+(vR[i]*vB[i]*uR[i]*-9.864592741628187E-7)+(vR[i]*uB[i]*uR[i]*1.6627196065567741E-7)+(vG[i]*vB[i]*uB[i]*-1.0652719655870072E-6)+(vG[i]*vB[i]*uR[i]*9.459822801296852E-7)+(vG[i]*uB[i]*uR[i]*8.557169024626118E-7)+(vB[i]*uB[i]*uR[i]*-3.9326828096977616E-7));
dbl[i] = (float) (-8.9357985776372E-4 +(vR[i]*0.0016325176946251762)+(vG[i]*0.009600884863818781)+(vB[i]*-0.0013736144281177522)+(uB[i]*6.142864633439507E-4)+(uR[i]*-5.894613503258471E-4)+(vR[i]*vG[i]*-4.729666927515018E-6)+(vR[i]*vB[i]*1.9844181184876184E-8)+(vR[i]*uB[i]*-5.2174296558447164E-5)+(vR[i]*uR[i]*6.101744867817176E-5)+(vG[i]*vB[i]*7.160791404035667E-6)+(vG[i]*uB[i]*7.364488502263283E-5)+(vG[i]*uR[i]*-1.0280136287743636E-4)+(vB[i]*uB[i]*-3.058874009665985E-5)+(vB[i]*uR[i]*5.276757512688384E-5)+(uB[i]*uR[i]*-1.0525690505984083E-6)+(vR[i]*vG[i]*vB[i]*-9.076005292418881E-9)+(vR[i]*vG[i]*uB[i]*-8.247355266556202E-8)+(vR[i]*vG[i]*uR[i]*2.9444677235249354E-7)+(vR[i]*vB[i]*uB[i]*2.117404036832909E-6)+(vR[i]*vB[i]*uR[i]*-2.468458492114994E-6)+(vR[i]*uB[i]*uR[i]*-2.997801007648404E-8)+(vG[i]*vB[i]*uB[i]*-2.0362759249368716E-6)+(vG[i]*vB[i]*uR[i]*2.1171352255758945E-6)+(vG[i]*uB[i]*uR[i]*2.5662525631110725E-7)+(vB[i]*uB[i]*uR[i]*-1.7941317060691475E-7));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
outStack.addSlice("uv", uv);
outStack.addSlice("dbl", dbl);
new ImagePlus("Output", outStack).show();

}
}
